rollno = input("Enter the roll number :")
name = input("Enter the name :")
marks1 = float(input("Enter the marks in subject 1 :"))
marks2 = float(input("Enter the marks of subject 2 :"))
marks3 = float(input("Enter the marks of subject 3 :"))
print("Result Sheet")
print(f"roll no : {rollno}")
print(f"Name : {name}")
print(f"Subject 1 : {marks1}")
print(f"Subject 2 : {marks2}")
print(f"Subject 3 : {marks3}")
print(f"Total Marks :{marks1+marks2+marks3}")
print(f"Average : {(marks1+marks2+marks3)/3}")
